development:
  rest_password: 'gfajdScjg9sjjvDfjffajdScjg9sjjsdjfjdfrjzzzzz' # a password for restful interaction with the webinterface - it's a shared secret.
  title: Inki Development Version
  scrollyness: true # if set to true, the webinterface will be more scrolling, not good for mobile phones
  brand: Inki
  auth_source: yaml # ldap | database | yaml
  languages:
    en: English
    de: Deutsch

production:
  rest_password: 'gfajdScjg9sjjvDfjffajdScjg9sjjsdjfjdfrjzzzzz' # a password for restful interaction with the webinterface - it's a shared secret.
  title: Inki Database
  scrollyness: false
  brand: Inki
  auth_source: ldap # ldap | database | yaml
  languages:
    en: English
    de: Deutsch
